CREATE DATABASE IF NOT EXISTS `investment_options`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `investment_options`;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  user_id CHAR(36) PRIMARY KEY,
  currency VARCHAR(16) NOT NULL DEFAULT 'JMD',
  dark_mode BOOLEAN NOT NULL DEFAULT FALSE,
  land_goal DECIMAL(18,2) NOT NULL DEFAULT 6000000,
  land_savings DECIMAL(18,2) NOT NULL DEFAULT 0,
  assets JSON NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_settings_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS snapshots (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  month VARCHAR(7) NOT NULL,
  invested DECIMAL(18,2) NOT NULL DEFAULT 0,
  value DECIMAL(18,2) NOT NULL DEFAULT 0,
  income DECIMAL(18,2) NOT NULL DEFAULT 0,
  fees DECIMAL(18,2) NOT NULL DEFAULT 0,
  realized DECIMAL(18,2) NOT NULL DEFAULT 0,
  inflation DECIMAL(8,4) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  assets JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_snapshots_user_month (user_id, month),
  INDEX idx_snapshots_user_month (user_id, month),
  CONSTRAINT fk_snapshots_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
